AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - prod
    Default: prod
    Description: Stage that can be added to resource names

Resources:
  Service1Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: service1/
      Runtime: nodejs4.3
      Policies: AWSLambdaBasicExecutionRole
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            Path: /service1{proxy+}
            Method: ANY
  Service2Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: service2/
      Runtime: nodejs4.3
      Policies: AWSLambdaBasicExecutionRole
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            Path: /service2{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: !Sub 'ApiUrl-${Stage}'
